"""Repository QA checks in the spirit of Aqua.jl's tests (Python port).

Aqua.jl tests the *quality* of a Julia package's metadata and public API:
dependency integrity, absence of undefined imports, and public-API
consistency. This module brings the same ideas to a Python project:

- every module under the package directory imports cleanly;
- the public API declared in ``__all__`` actually exists on the package;
- no module imports a missing *internal* sibling (dependency completeness
  against ``pyproject.toml`` is deptry's static job).
"""

import importlib
import pkgutil
from pathlib import Path
from typing import cast

import open_law as pkg

TOP = Path(__file__).resolve().parent.parent
PKG_DIR = TOP / "src/open_law"

# _version.py is generated by setuptools-scm at build time.
_EXCLUDED = {"open_law._version"}


def _package_modules() -> list[str]:
    """Dotted names of every importable module under the package directory."""
    return sorted(
        info.name for info in pkgutil.walk_packages([str(PKG_DIR)], prefix="open_law.") if info.name not in _EXCLUDED
    )


def test_every_module_imports() -> None:
    """Importing any module in the package must not raise."""
    for name in _package_modules():
        importlib.import_module(name)


def test_public_api_declared_in_all_is_importable() -> None:
    """Names in __all__ resolve to real attributes of the package."""
    # getattr returns Any; cast to a concrete tuple so the QA test itself
    # stays clean under basedpyright (reportAny / reportUnknownVariableType).
    all_names = cast("tuple[str, ...]", getattr(pkg, "__all__", ()))
    for name in all_names:
        assert hasattr(pkg, name), f"{name!r} missing from the package"


def test_no_obviously_undefined_internal_imports() -> None:
    """A package module must not import a sibling module that does not exist.

    Importing every module (test_every_module_imports) already fails on a
    missing *third-party* dependency; this adds a guard for missing
    *internal* modules, which a bad merge can leave dangling. It is shallow
    by design — dependency completeness against pyproject.toml is deptry's
    static job.
    """
    pkg_name = "open_law"
    for name in _package_modules():
        try:
            importlib.import_module(name)
        except ImportError as exc:
            missing = exc.name or ""
            if missing == pkg_name or missing.startswith(f"{pkg_name}."):
                raise


def test_charter_and_fetcher_contact_wired() -> None:
    """CHARTER.md exists and the fetcher carries a contactable User-Agent.

    The Good-future charter is enforced by shape, not prose: every fetch
    goes through fetcher.py, whose User-Agent identifies the project plus
    a contact address (FETCHER_CONTACT env or CONTACT_PLACEHOLDER).
    """
    assert (TOP / "CHARTER.md").exists(), "scraping layer must ship CHARTER.md"
    fetcher_src = (PKG_DIR / "fetcher.py").read_text(encoding="utf-8")
    assert "CONTACT_PLACEHOLDER" in fetcher_src
    assert "FETCHER_CONTACT" in fetcher_src
